image:
  file: .gitpod.dockerfile

tasks:
  - name: Setup
    init: |
      npm i
      npm i -g ganache-cli
      ganache-cli --accounts 10 --gasLimit 6721975000
      gp sync-done setup
  - name: Frontend
    init: |
      gp sync-await setup
      truffle migrate --network=develop --reset
      cd client
      npm i
    command: npm start

ports:
  - port: 3000
    onOpen: open-browser
